// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';

import { defineConfig, env } from 'prisma/config';

const NODE_ENV = process.env.NODE_ENV ?? 'development';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed:
      NODE_ENV === 'development'
        ? 'tsx prisma/dev.seed.ts'
        : 'tsx prisma/prod.seed.ts',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
